export const disallowed_items = [
    "minecraft:dirt",
    "minecraft:sand",
    "minecraft:cobblestone_wall",
    "minecraft:sandstone",
    "minecraft:red_sandstone",
    "minecraft:monster_egg",
    "minecraft:stonebrick",
    "minecraft:stone_block_slab",
    "minecraft:stone_block_slab2",
    "minecraft:stone_block_slab3",
    "minecraft:stone_block_slab4",
    "minecraft:double_stone_block_slab",
    "minecraft:double_stone_block_slab2",
    "minecraft:double_stone_block_slab3",
    "minecraft:double_stone_block_slab4",
    "minecraft:quartz_block",
    "minecraft:tallgrass",
    "minecraft:double_plant",
    "minecraft:yellow_flower",
    "minecraft:coral_fan_hang",
    "minecraft:coral_fan_hang2",
    "minecraft:coral_fan_hang3",
    "minecraft:skull",
    "minecraft:bed",
    "minecraft:chemistry_table",
    "minecraft:anvil",

    "minecraft:empty_map",
    "minecraft:filled_map",
    "minecraft:tropical_fish_bucket",
    "minecraft:axolotl_bucket",
    "minecraft:salmon_bucket",
    "minecraft:banner",
    "minecraft:potion",
    "minecraft:splash_potion",
    "minecraft:lingering_potion",
    "minecraft:goat_horn",
    "minecraft:arrow",
    "minecraft:firework_star",
    "minecraft:firework_rocket",
    "minecraft:leather_horse_armor",
    "minecraft:lodestone_compass",
    "minecraft:shield",

    "minecraft:chainmail_helmet",
    "minecraft:chainmail_chestplate",
    "minecraft:chainmail_leggings",
    "minecraft:chainmail_boots",

    "minecraft:diamond_helmet",
    "minecraft:diamond_chestplate",
    "minecraft:diamond_leggings",
    "minecraft:diamond_boots",

    "minecraft:golden_helmet",
    "minecraft:golden_chestplate",
    "minecraft:golden_leggings",
    "minecraft:golden_boots",

    "minecraft:iron_helmet",
    "minecraft:iron_chestplate",
    "minecraft:iron_leggings",
    "minecraft:iron_boots",

    "minecraft:leather_helmet",
    "minecraft:leather_chestplate",
    "minecraft:leather_leggings",
    "minecraft:leather_boots",

    "minecraft:netherite_helmet",
    "minecraft:netherite_chestplate",
    "minecraft:netherite_leggings",
    "minecraft:netherite_boots",

    "minecraft:turtle_helmet",

    "hatchi:bundlepack",

    "minecraft:black_shulker_box",
    "minecraft:blue_shulker_box",
    "minecraft:brown_shulker_box",
    "minecraft:cyan_shulker_box",
    "minecraft:gray_shulker_box",
    "minecraft:green_shulker_box",
    "minecraft:light_blue_shulker_box",
    "minecraft:light_gray_shulker_box",
    "minecraft:lime_shulker_box",
    "minecraft:magenta_shulker_box",
    "minecraft:orange_shulker_box",
    "minecraft:pink_shulker_box",
    "minecraft:purple_shulker_box",
    "minecraft:red_shulker_box",
    "minecraft:undyed_shulker_box",
    "minecraft:white_shulker_box",
    "minecraft:yellow_shulker_box",
]